### ISSUE TITLE
Don't rebuild in development

### ISSUE THREAD

**Issue by julianrubisch** [julianrubisch/bridgetown-media-transformation#5]
currently everything is done in a `post_write` hook, which works great, but also means that every time I change a running site, every image is re-transformed  💤

**Comment by jaredcwhite** [comment]
Could you save a cache file with fingerprint/hashes of the source images, so it'll skip over any image file that hasn't changed? But then it'd also have to make sure the transformed images in `output` aren't deleted either. Hmm.

**Comment by julianrubisch** [comment]
Yeah exactly. I thought about maybe storing (and retrieving) them to/from a different location outside `output`

**Comment by julianrubisch** [comment]
Alternatively just bypass in development, but then again you want to test your responsive images...

**Comment by julianrubisch** [comment]
Fixed by moving to `_bridgetown`, for now, thanks @andrewmcodes
